### PR TITLE
Support resume for GIF, WEBP and custom resume time

### PR DESCRIPTION
**Pull request by cheadrian**
- Resume after casting GIF or WEBP images format.
- Let user to chose the timeout before the script will resume images and dashboard.

### CODE REVIEW

**Comment by TheFes** [comment]
I kinda specifically created two different delays, so users can choose to use a different delay for images and dashboards. However, I agree that might not be needed.
However, it also doesn't make sense to use 2 variables in the helper script then.


[lines 886-887](https://github.com/TheFes/HA-configuration/blob/main/include/script/00_general/google_cast/google_home_resume.yaml#L886-L887) could be changed to:
```yaml
                resume_delay: "{{ resume_delay if resume_delay is defined and image_delay else 20 }}"
```

[lines 976-979](https://github.com/TheFes/HA-configuration/blob/main/include/script/00_general/google_cast/google_home_resume.yaml#L976-L979) could be changed to:
```yaml
        - if: "{{ image or dashboard_cast }}"
          then:
            - delay: "{{ resume_delay }}"
```

Could you add that to the PR?

**Comment by cheadrian** [comment]
Can you check? 
I propose to use `default_resume_delay` in  place of `image_delay` and `dashboard_cast_delay`. Might become handy if there's additional functions in the future that needs delay due to improve readability. 
Tested it on Nest Hub 2nd and it works fine.

**Comment by TheFes** [comment]
I have some doubts if the `default_resume_delay` is used properly to send the delay to the helper script.
I think it should be something like this

```jinja
{% if resume_delay is defined and resume_delay %}
  {{ resume_delay }}
{% elif default_resume_delay is defined and default_resume_delay %}
  {{ default_resume_delay }}
{% else %}
  20
{% endif %}
```

**Comment by TheFes** [comment]
Thanks, I will merge this tomorrow, together with an update to the docs (both on GitHub and on the HA community)

**Pull request merged**
